[book]
authors = ["cluster-api-provider-stackit contributors"]
language = "en"
src = "src"
title = "Cluster API Provider STACKIT"

[output.html]
git-repository-url = "https://github.com/stackitcloud/cluster-api-provider-stackit"
edit-url-template = "https://github.com/stackitcloud/cluster-api-provider-stackit/edit/main/docs/{path}"
no-section-label = true
admonitions = true

[preprocessor.embed]
command = "mdbook-embed"

[preprocessor.tabulate]
command = "mdbook-tabulate"
